global:
 resolve_timeout: 10s
 slack_api_url: 'https://hooks.slack.com/services/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'
 
route:
 receiver: 'slack-notifications'
 
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#prometheus-grafana-lab'
    send_resolved: true
